import type { NextPage } from 'next';
import { Builder, Workspace, item, branch } from 'build-ui';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import AlertTools from '../ui/alert/AlertTools';
import AlertView from '../ui/alert/AlertView';
import SectionView from '../ui/section/SectionView';

const MyBuilder = () => {
	const section = item({
		type: 'Section',
		props: {},
	});
	const tree = branch(section);
	const view = {
		Section: SectionView,
		Alert: AlertView,
	};
	return (
		<Builder initialTree={tree}>
			<Workspace view={view} />
			<AlertTools />
		</Builder>
	);
};

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to <a href='https://nextjs.org'>Next.js!</a>
				</h1>

				<p className={styles.description}>
					Get started by editing{' '}
					<code className={styles.code}>pages/index.tsx</code>
				</p>

				<div className={styles.grid}>
					<MyBuilder />
				</div>
			</main>

			<footer className={styles.footer}>
				<a
					href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
					target='_blank'
					rel='noopener noreferrer'
				>
					Powered by{' '}
					<span className={styles.logo}>
						<Image
							src='/vercel.svg'
							alt='Vercel Logo'
							width={72}
							height={16}
						/>
					</span>
				</a>
			</footer>
		</div>
	);
};

export default Home;
